# Node.js application

stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: "production"

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm test

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://staging.example.com
  script:
    - echo "Deploying to staging"
    # Add your deployment commands here

deploy_production:
  stage: deploy
  environment:
    name: production
    url: https://www.example.com
  script:
    - echo "Deploying to production"
    # Add your deployment commands here
